
package com.lyra.vads.ws.v5;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "v5", targetNamespace = "http://v5.ws.vads.lyra.com/", wsdlLocation = "https://secure.payzen.eu/vads-ws/v5?wsdl")
public class V5
    extends Service
{

    private final static URL V5_WSDL_LOCATION;
    private final static WebServiceException V5_EXCEPTION;
    private final static QName V5_QNAME = new QName("http://v5.ws.vads.lyra.com/", "v5");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://secure.payzen.eu/vads-ws/v5?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        V5_WSDL_LOCATION = url;
        V5_EXCEPTION = e;
    }

    public V5() {
        super(__getWsdlLocation(), V5_QNAME);
    }

    public V5(WebServiceFeature... features) {
        super(__getWsdlLocation(), V5_QNAME, features);
    }

    public V5(URL wsdlLocation) {
        super(wsdlLocation, V5_QNAME);
    }

    public V5(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, V5_QNAME, features);
    }

    public V5(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public V5(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentAPI
     */
    @WebEndpoint(name = "PaymentAPIImplPort")
    public PaymentAPI getPaymentAPIImplPort() {
        return super.getPort(new QName("http://v5.ws.vads.lyra.com/", "PaymentAPIImplPort"), PaymentAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentAPI
     */
    @WebEndpoint(name = "PaymentAPIImplPort")
    public PaymentAPI getPaymentAPIImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://v5.ws.vads.lyra.com/", "PaymentAPIImplPort"), PaymentAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (V5_EXCEPTION!= null) {
            throw V5_EXCEPTION;
        }
        return V5_WSDL_LOCATION;
    }

}
